### ISSUE TITLE
Problem in Debug mode... 

### ISSUE THREAD

**Issue by Hadron4biz** [buke/odoo-web-pdf-preview-print#11]
In debug mode in Odoo there are problems
`Uncaught SyntaxError: Unexpected token T
http://my.domain.com/web?debug=#id=13&view_type=form&model=account.invoice&action=192&active_id=1&menu_id=117:1
Traceback:
SyntaxError: Unexpected token T
    at Object.parse (native)
    at HTMLIFrameElement.<anonymous> (http://my.domain.com/web/static/src/js/framework/ajax.js:230:40)
    at HTMLIFrameElement.jQuery.event.dispatch (http://my.domain.com/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLIFrameElement.elemData.handle (http://my.domain.com/web/static/lib/jquery/jquery.js:4309:63)`

**Comment by firmansi** [comment]
I also have similar problem with his
`Uncaught SyntaxError: Unexpected token T in JSON at position 0
http://192.168.1.66:8069/web#id=5&view_type=form&model=account.invoice&menu_id=145&action=191:1
Traceback:
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (http://192.168.1.66:8069/web/static/src/js/framework/ajax.js:230:40)
    at HTMLIFrameElement.dispatch (http://192.168.1.66:8069/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLIFrameElement.elemData.handle (http://192.168.1.66:8069/web/static/lib/jquery/jquery.js:4309:63)`

can anybody help why?
